export {
  initAnalytics as initPixel,
  trackPageView,
  trackViewContent,
  trackAddToCart,
  trackInitiateCheckout,
  trackLead,
  trackContact,
  trackWhatsAppClick,
  trackPhoneClick,
  trackPurchase,
  trackSearch,
  trackCompleteRegistration,
  trackCustomEvent,
} from "./analytics";